name: visualbench
channels:
  - conda-forge
dependencies:
  - python
  - pytorch # DIFFERENT FROM PIP!!!!!!!!!!!!!!!!!!!!!
  - numpy
  - scipy
  - opencv # different from PIP!
  - matplotlib
  - more_itertools

  # - pip
  # - pip:
  #   - some-pip-only-package # For packages only on PyPI