# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12","3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: run pytest ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install scipy
        python -m pip install opencv-python
        python -m pip install matplotlib
        python -m pip install more_itertools
        python -m pip install git+https://github.com/inikishev/visualbench.git
    - name: Test with pytest
      run: |
        pytest
